## LOCAL HOST

## GET ALL EMPLOYEES
GET http://localhost:3000/employees

### GET EMPLOYEE BY ID
GET http://localhost:3000/employees/67065a4be2b0201fe358f468

### CREATE EMPLOYEE
POST http://localhost:3000/employees HTTP/1.1
content-type: application/json

{
    "firstName": "CreateFirst",
    "lastName": "CreateLast",
    "email": "Create@gmail.com",
    "birthday": "Create, 2000",
    "startDate": "Create, 2024",
    "wage": "Create 15",
    "position": "Create clerk",
    "team": "Create Service"
}

### UPDATE EMPLOYEE
PUT http://localhost:3000/employees/67065ee5e1f72cc6e23b421e HTTP/1.1
content-type: application/json

{
    "firstName": "UpdateFirst",
    "lastName": "UpdateLast",
    "email": "Update@gmail.com",
    "birthday": "Update, 2000",
    "startDate": "Update, 2024",
    "wage": "Update 15",
    "position": "Update clerk",
    "team": "Update Service"
}

### DELETE EMPLOYEE
DELETE http://localhost:3000/employees/67065ee5e1f72cc6e23b421e
content-type: application/json



